### ISSUE TITLE
Error with urlparse

### ISSUE THREAD

**Issue by TerenceJohny** [srid99/einthusan-dl#10]
Im using pyhton 3.5.2 and get the following error.... 
C:\Users\einthusan-dl-master>einthusan-dl.bat "http://www.einthusan.com/movies/watch.php?malayalammoviesonline=Action+Hero+Biju&lang=malayalam&id=2939#"
Traceback (most recent call last):
  File "C:\Users\einthusan-dl-master\einthusan-dl", line 4, in <module>
    from einthusan import einthusan_dl
  File "C:\Users\einthusan-dl-master\einthusan\einthusan_dl.py", line 18, in <module>
    from urlparse import urljoin
ImportError: No module named 'urlparse'

**Comment by neurogroups** [comment]
seems to be an issue with python3. Changing to urllib.parse works for me.

**Comment by neurogroups** [comment]
Edit: seems to be an issue with python3. Changing to urllib.parse works.

**Comment by srid99** [comment]
Does it work with python2 ? If it works then could you send a pull request with the fix ?

**Comment by dhoom37** [comment]
from urlparse import urljoin,  change it to from urllib.parse import urljoin in einthusan_dl.py file

**Comment by neurogroups** [comment]
Sorry i didn't get back on it.
I'm not too familiar with github. I'll try to figure this out.

Zulfi

**Comment by meher1109** [comment]
I had the same error. After making changes suggested by dhoom37, I am getting the following error now.

Traceback (most recent call last):
  File "C:\Users\rahul123\Downloads\einthusan-dl-master\einthusan-dl-master\\einthusan-dl", line 4, in <module>
    from einthusan import einthusan_dl
  File "C:\Users\rahul123\Downloads\einthusan-dl-master\einthusan-dl-master\einthusan\einthusan_dl.py", line 20, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by srid99** [comment]
@neurogroups and @meher1109 I have updated the script to work with the new format of the site (#19). The problems you mentioned should not be there. I will close this issue for now.

**Comment by neurogroups** [comment]
Great, thanks man!

Sincerely,

Neurogroups
