### ISSUE TITLE
Blu-ray Support

### ISSUE THREAD

**Issue by VinnyPutty** [srid99/einthusan-dl#14]
Current version doesn't work when trying to download a blu-ray version such as from http://www.einthusan.com/movies/watch.php?telugumoviesonline=Naayak&lang=telugu&id=1860&bluray=true. As I'm still going through the code and trying to figure out exactly how the process of selecting the correct stream works, I wasn't able to identify any specific reasons for this failure. I'll continue looking into this, but just wanted to bring it up as I believe it would be valuable functionality.

Edit: grammar

**Comment by YaarPatandarAA** [comment]
Yeah I would like this feature also, currently looking through code as well. Please do post if you make any headway.

**Comment by srid99** [comment]
@VinnyPutty and @YaarPatandarAA I just updated the script to support the new format. Not sure if this feature is still available. For now, I will go ahead and close this issue. But if you find BluRay support available then let's reopen this issue.
