### ISSUE TITLE
Unhandled exception:  No connection adapters were found

### ISSUE THREAD

**Issue by dhoom37** [srid99/einthusan-dl#15]
C:\Users\siddharth\Desktop\einthusan-dl-master>einthusan-dl --path=C:\downloads\
movies "<http://einthusan.com/movies/watch.php?tamilmoviesonline=Mankatha&lang=t
amil&id=579>"
2016-10-13 08:57:00,610 Downloading movie from page : <http://einthusan.com/movi
es/watch.php?tamilmoviesonline=Mankatha&lang=tamil&id=579>
2016-10-13 08:57:00,612 Unhandled exception: No connection adapters were found f
or '<http://einthusan.com/movies/watch.php?tamilmoviesonline=Mankatha&lang=tamil
&id=579>'

C:\Users\siddharth\Desktop\einthusan-dl-master>

**Comment by srid99** [comment]
@dhoom37 I just updated the script to support the new format (#19). This issue shouldn't be there anymore. I will go ahead and close this issue. Let me know if it still persist.
