### ISSUE TITLE
"403 Forbidden" error

### ISSUE THREAD

**Issue by d3c1978** [srid99/einthusan-dl#16]
A sample run, produced the following error:

> $ ./einthusan-dl "http://einthusan.com/movies/watch.php?telugumoviesonline=Singamalai&lang=telugu&id=4021" --wget
> 2016-10-20 15:17:11,224 Downloading movie from page : http://einthusan.com/movies/watch.php?telugumoviesonline=Singamalai&lang=telugu&id=4021
> 2016-10-20 15:17:11,227 Starting new HTTP connection (1): einthusan.com
> 2016-10-20 15:17:11,262 Downloaded http://einthusan.com/movies/watch.php?telugumoviesonline=Singamalai&lang=telugu&id=4021 (28647 bytes)
> 2016-10-20 15:17:11,278 Starting new HTTP connection (1): cdn.einthusan.com
> 2016-10-20 15:17:11,299 Movie url: http://75.126.39.83/einthusancom/cold/D4021.mp4.m3u8?e=1477012551&md5=dBylyDdeMmtyXsLRLaGV-w
> 2016-10-20 15:17:11,300 Starting new HTTP connection (1): 75.126.39.83
> 2016-10-20 15:17:11,460 Downloading: Singamalai
> --2016-10-20 15:17:11--  http://75.126.39.83/einthusancom/cold/D4021.mp4.ts?start=0.000&end=9663.680&e=1477012551&md5=dBylyDdeMmtyXsLRLaGV-w
> Connecting to 75.126.39.83:80... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2016-10-20 15:17:11 ERROR 403: Forbidden.
> 2016-10-20 15:17:11,542 Successfully downloaded the movie Singamalai. Took 81675 microseconds
> $

**Comment by srid99** [comment]
@d3c1978 I updated the script to support the new format of their site (#19). I would expect things to work fine. I will go ahead and close this issue. If you still encounter similar issues let's either reopen this or create another issue.
