### ISSUE TITLE
help with wget?

### ISSUE THREAD

**Issue by YaarPatandarAA** [srid99/einthusan-dl#17]
I need a guidance on how to use WGET in this Script. How can I download using external downloader.

I am having issues with downloading because it downloads to a certain point then gets stuck and the download crashes and i have to restart from 0%. Thus I have to monitor the downloads so that I don't have the command stuck for hours to end, thinking that it is probably still downloading.

**Comment by srid99** [comment]
@YaarPatandarAA Do you got it working ? I will close this issue for now. We can reopen it if you like to give a try :)
