### ISSUE TITLE
Script fails on Windows if movie name contains a colon

### ISSUE THREAD

**Issue by monemihir** [srid99/einthusan-dl#18]
http://www.einthusan.com/movies/watch.php?marathimoviesonline=Lokmanya%3A+Ek+Yug+Purush&lang=marathi&id=2985

Tried to download this movie which has a **:** in it's name.

Since the name contains a colon Windows is unable to create a folder with that name.

A simple solution would be to replace all special characters like these with a underscore.

**Comment by srid99** [comment]
@monemihir I see the problem (I myself use Linux so never come across all those pains you see in Windows :)) Anyways I made changes so that it only takes alphanumeric characters and other characters will be converted into underscore.

Between, sorry for the delay and thanks for reporting :)
