### ISSUE TITLE
New format - Please update the script

### ISSUE THREAD

**Issue by dishoom-git** [srid99/einthusan-dl#19]
Hi,

Thanks for creating the script.
There are updates to the url now, so can you please update the script to make it work according to the new format?
Thanks a ton! :)

**Comment by srid99** [comment]
Yeah, I noticed the changes. Not getting enough time to make it work with the new changes. Maybe this weekend :)

**Comment by dishoom-git** [comment]
Sure, thanks man!

**Comment by srid99** [comment]
As promised, I had a look and seems they made quite some changes. Tricky. Good news is it is fixable. I will try to push my changes within this week :)

**Comment by srid99** [comment]
@dishoom-git so here we go... Updated the script. Can you give a try and let me know?

**Comment by dishoom-git** [comment]
Works perfectly! again, thanks a ton, appreciate your efforts :)
