### ISSUE TITLE
Cannot download using this script.

### ISSUE THREAD

**Issue by kvsrkrishnan** [srid99/einthusan-dl#22]
Here's the link: https://einthusan.tv/movie/watch/5h4X/?lang=tamil
What the script is looking at: https://s35.einthusan.tv/einthusancom/hot/D5h4X.mp4?e=1526736499&md5=LztPQss27B8K8KRoUwSGSA

What the script must be looking at:
https://s39.einthusan.tv/einthusancom/hot/D5h4X.mp4?e=1526734896&md5=UDpBbzi6xfdVzchMvdWk_A

**Comment by srid99** [comment]
Thanks for reporting. I made a fix by being reducing the scope of getting the title name. Can you check and if it works then also close the issue?

**Comment by srid99** [comment]
Closing the issue since there is no response. Do reopen the issue if the issue still exist.
