### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VasanthaAtai** [srid99/einthusan-dl#24]
Hi. Is this still working?

**Comment by srid99** [comment]
I think so. It didn't for you?

**Comment by VasanthaAtai** [comment]
It gave me this error=Unhandled exception: No module named '__main__.downloaders'; '__main__' is not a package

**Comment by VasanthaAtai** [comment]
same as the first person.

**Comment by srid99** [comment]
In which environment are you trying? Did you followed the instruction in read me? Which python version are you using?

**Comment by VasanthaAtai** [comment]
I am using a VPN and using the latest version of python in windows 10 latest version

**Comment by srid99** [comment]
Can you specify the version of python? Is it 3.7.2?

**Comment by srid99** [comment]
I just tried with python 2.7.16 and seems to work fine.

**Comment by VasanthaAtai** [comment]
No. It is 3.7.4.

**Comment by VasanthaAtai** [comment]
Help me. I am using a VPN to connect to einthusan and I followed the steps correctly but still, something is wrong

**Comment by srid99** [comment]
I don't have a windows environment. So, I can't test or reproduce this. Can you check the bat file? And try to enclose the command with double quotes. Ex: `python "%~dp0\einthusan-dl" %*`

**Comment by VasanthaAtai** [comment]
How to do that?

**Comment by srid99** [comment]
You must be executing this using the `einthusan-dl.bat` file. Open it using an editor and change the command as mentioned above.

**Comment by VasanthaAtai** [comment]
![image](https://user-images.githubusercontent.com/53982927/62827686-de7bed00-bc06-11e9-9f3d-36a8429b29e8.png)

**Comment by VasanthaAtai** [comment]
Next step?

**Comment by srid99** [comment]
Well, run the command from the command line (from CMD).

**Comment by VasanthaAtai** [comment]
![image](https://user-images.githubusercontent.com/53982927/62827705-3fa3c080-bc07-11e9-9b14-68aa1b8ad4af.png)

**Comment by VasanthaAtai** [comment]
Hey. Did you see that?

**Comment by srid99** [comment]
Go back one level of the folder and run the einthusan-dl.bat file

**Comment by VasanthaAtai** [comment]
I clicked the bat file but nothing happens. 
![image](https://user-images.githubusercontent.com/53982927/62827729-b93bae80-bc07-11e9-8c3f-761fa31598cd.png)

**Comment by srid99** [comment]
You shouldn't click but run it from the command line.

**Comment by VasanthaAtai** [comment]
what is the command for that?

**Comment by VasanthaAtai** [comment]
tell me

**Comment by srid99** [comment]
The command is `einthusan-dl.bat`. Follow the step mentioned in the URL (follow method 2) on how to run a bat file from command line. Don't forget to run it from the `einthusan-dl-master` folder.

https://www.wikihow.com/Run-a-Batch-File-from-the-Command-Line-on-Windows

**Comment by VasanthaAtai** [comment]
![image](https://user-images.githubusercontent.com/53982927/62827755-aaa1c700-bc08-11e9-920b-96267a0decf0.png)
what should I type next?

**Comment by srid99** [comment]
It's in the readme. Eg: `einthusan-dl.bat "https://einthusan.ca/movie/watch/XXXX"`

**Comment by VasanthaAtai** [comment]
It is working. Thank you

**Comment by srid99** [comment]
Nice
