### ISSUE TITLE
ERROR:root:Unhandled exception: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by d3c1978** [srid99/einthusan-dl#3]
When I try to test the script, I get the error:
ERROR:root:Unhandled exception: 'NoneType' object is not callable

I picked the following URL to test:
"http://www.einthusan.com/movies/watch.php?telugumoviesonline=Veeraa&lang=telugu&id=3014"

And used it raw, with --curl and with --wget, with the same issue. 

Mind checking this?

**Comment by krackers** [comment]
Broken again. It looks like they are now dynamically getting the movie url.

**Comment by srid99** [comment]
@krackers You are correct. Seems like they do a lookup for the video URL.

They query http://cdn.einthusan.com/geturl/{movie-id}/hd/London%2CToronto%2CDallas%2CWashington%2CSan%2CSydney/

Actually they made our work easy. No need for screen scrapping just use their API :P

**Comment by srid99** [comment]
@krackers Fixed. Can you try now ?

**Comment by krackers** [comment]
@srid99 Yeah I looked at the page requests and saw the same. Haven't tested your implementation but it should work fine.

Nice of them to provide the api though! :D

**Comment by srid99** [comment]
Closing the issue then..
