### ISSUE TITLE
.m3u8 instead of .mp4

### ISSUE THREAD

**Issue by i-love-coding** [srid99/einthusan-dl#5]
I don't think it's a script fault, but now it seems to be getting a .m3u8 playlist instead of a .mp4 file, this is the answer I got when requesting the movie with id = 2936

http://169.50.64.99/einthusancom/hot/D2936.mp4.m3u8?st=uk980VAK2bKv5nHZvX_GGg&e=1468613125

**Comment by srid99** [comment]
That's true. Seems like they use a new format to stream the videos. As you can see, in the m3u, it has various time sequence of the videos. To get this working we have to find the end time of the video and download it in one go. Seems like possible. Will give a try soon..

**Comment by srid99** [comment]
Apparently my "try soon" never happened but @aaiyer got it fixed :) Try it again (after updating your repo). Works like charm (again).
