### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jasondevj** [srid99/einthusan-dl#8]
Hi,

I tried to run the script today and it does not work, I get the following error 

2016-08-14 10:22:11,803 Starting new HTTP connection (2): 169.50.64.86
2016-08-14 10:22:12,594 Probably the file is missing from the AWS repository... waiting.
Error downloading, will retry in 4 seconds ...

**Comment by sayaara** [comment]
Yes I too got the same error

**Comment by srid99** [comment]
Seems like they enabled cross domain policy. Let me check if we can overcome this ;)

**Comment by srid99** [comment]
Token is missing while constructing the URL. Fixed and should work again :)
